#ifdef MZNT_RENDERER_SWITCHBOARD_ENABLED

#undef MZNT_RHI_FN_SIX_ARG
#undef MZNT_RHI_FN_FIVE_ARG
#undef MZNT_RHI_FN_FOUR_ARG
#undef MZNT_RHI_FN_THREE_ARG
#undef MZNT_RHI_FN_TWO_ARG
#undef MZNT_RHI_FN_ONE_ARG
#undef MZNT_RHI_SWITCH_SIX_ARG
#undef MZNT_RHI_SWITCH_FIVE_ARG
#undef MZNT_RHI_SWITCH_FOUR_ARG
#undef MZNT_RHI_SWITCH_THREE_ARG
#undef MZNT_RHI_SWITCH_TWO_ARG
#undef MZNT_RHI_SWITCH_ONE_ARG
#undef MZNT_RHI_FN_UNSUPPORTED_BRANCH
#undef MZNT_RHI_FN_METAL_BRANCH
#undef MZNT_RHI_FN_DX12_BRANCH
#undef MZNT_RHI_FN_VK_BRANCH
#undef MZNT_RHI_FN_NULL_BRANCH
#undef MZNT_RHI_ARG_CHECK_DYNA
#undef MZNT_RHI_ARG_CHECK_STAT
#undef MZNT_RHI_RET_END_DYNA
#undef MZNT_RHI_RET_END_STAT
#undef MZNT_RHI_RET_START_DYNA
#undef MZNT_RHI_RET_START_STAT
#undef MZNT_RHI_ARG_DECL_DYNA
#undef MZNT_RHI_ARG_DECL_STAT
#undef MZNT_RHI_ARG_PASS_DYNA
#undef MZNT_RHI_ARG_PASS_STAT

#undef MZNT_RENDERER_SWITCHBOARD_ENABLED

#endif
